"""Dependency inversion at history, storage, tokenization, and configuration boundaries."""

from pathlib import Path
from typing import Protocol

from .contracts import BaselineLink, CostCoverage, Emission, Exposure, ImportRequest, TaskObservation


class HistoryReader(Protocol):
    def read(self, request: ImportRequest, observed_at: str) -> TaskObservation: ...


class ExposureCounter(Protocol):
    def count(self, texts: tuple[str, ...]) -> Exposure: ...


class MeasurementRepository(Protocol):
    def capture_draft(self, path: Path, task_id: str) -> None: ...
    def draft_task(self, path: Path) -> str | None: ...
    def put(self, observation: TaskObservation) -> bool: ...
    def tasks(self) -> tuple[TaskObservation, ...]: ...
    def link(self, link: BaselineLink) -> None: ...
    def links(self, ref: str) -> tuple[BaselineLink, ...]: ...
    def coverage(self, ref: str) -> CostCoverage: ...
    def declare(self, coverage: CostCoverage) -> None: ...
    def emit(self, emission: Emission) -> None: ...
    def retain_since(self, timestamp: str) -> None: ...
