"""External boundaries consumed by application services; implementations live in infrastructure."""

from __future__ import annotations

from collections.abc import Callable, Mapping, Sequence
from contextlib import AbstractContextManager
from dataclasses import dataclass
from pathlib import Path
from typing import Protocol

from .domain import (
    Catalog,
    Evidence,
    Failure,
    InspectRequest,
    Job,
    JsonObject,
    Page,
    Run,
    Settings,
    Target,
    Workflow,
)


class SettingsStore(Protocol):
    def load(self) -> Settings: ...
    def save(self, settings: Settings) -> None: ...
    def update(self, change: Callable[[Settings], Settings]) -> Settings: ...


class WorkflowRepository(Protocol):
    def get(self, ref: str) -> Workflow: ...
    def search(
        self,
        query: str,
        *,
        environment: str | None = None,
        repository: str | None = None,
        platform: str | None = None,
        offset: int = 0,
        limit: int = 100,
    ) -> Sequence[Workflow]: ...
    def replace_catalog(self, name: str, workflows: Sequence[Workflow]) -> None: ...
    def add_draft(self, workflow: Workflow) -> None: ...


class BundleStore(Protocol):
    def load(self, directory: Path, catalog: str = "draft", revision: str | None = None) -> Workflow: ...
    def snapshot(self, workflow: Workflow) -> Workflow: ...
    def verify(self, workflow: Workflow) -> None: ...
    def discover(self, directory: Path) -> Sequence[Path]: ...


class CatalogSource(Protocol):
    def read(self, catalog: Catalog) -> tuple[Sequence[Workflow], str | None]: ...


class RunRepository(Protocol):
    def create(self, run: Run, request_id: str | None, fingerprint: str, lock_key: str | None) -> Run: ...
    def get(self, run_id: str) -> Run: ...
    def claim(self, run_id: str, owner: str) -> Run: ...
    def finish(self, run: Run, owner: str | None) -> None: ...
    def heartbeat(self, run_id: str, owner: str) -> None: ...
    def release_lock(self, run_id: str) -> None: ...
    def settled(self, run_id: str, release_lock: bool) -> None: ...
    def pending(self, limit: int = 100) -> Sequence[str]: ...
    def is_pending(self, run_id: str) -> bool: ...
    def set_pid(self, run_id: str, pid: int) -> None: ...
    def expired(self, cutoff: float) -> Sequence[Run]: ...
    def delete(self, run_id: str) -> None: ...


class ArtifactStore(Protocol):
    def prepare(self, job: Job) -> Path: ...
    def job(self, run_id: str) -> Job: ...
    def directory(self, run_id: str) -> Path: ...
    def save_result(self, run: Run) -> None: ...
    def evidence(self, run_id: str) -> Evidence | None: ...
    def save_evidence(self, evidence: Evidence) -> None: ...
    def request_cancel(self, run_id: str) -> None: ...
    def cancelled(self, run_id: str) -> bool: ...
    def remove(self, run_id: str) -> None: ...
    def page(self, request: InspectRequest) -> Page: ...
    def raw_evidence(self, run_id: str) -> Evidence: ...
    def scrub_inputs(self, run_id: str) -> None: ...
    def diagnostic(self, run_id: str, failure: Failure) -> None: ...
    def log(self, run_id: str, secrets: Sequence[str], max_bytes: int) -> LogSink: ...


class WorkerLauncher(Protocol):
    def start(self, run_id: str, environment: Mapping[str, str]) -> int: ...


class RunGuard(Protocol):
    def hold(self, run_id: str) -> AbstractContextManager[None]: ...
    def exclusive(self, run_id: str) -> AbstractContextManager[bool]: ...


class Host(Protocol):
    @property
    def platform(self) -> str: ...
    @property
    def environment(self) -> Mapping[str, str]: ...
    def command_exists(self, command: str, directory: Path, path: str) -> bool: ...
    def target(self, workspace: Path, environment: str) -> Target: ...
    def workspace_exists(self, workspace: Path) -> bool: ...
    def required_path_exists(self, workspace: Path, path: str) -> bool: ...


class Clock(Protocol):
    def epoch(self) -> float: ...
    def monotonic(self) -> float: ...
    def iso(self) -> str: ...
    def sleep(self, seconds: float) -> None: ...


class SchemaValidator(Protocol):
    def check_schema(self, schema: JsonObject) -> None: ...
    def validate(self, schema: JsonObject, value: JsonObject, code: str) -> None: ...


class CommandExecutor(Protocol):
    def execute(self, args: Sequence[str], timeout: float = 120, max_bytes: int = 67108864) -> bytes: ...


class LogSink(Protocol):
    def write(self, stream: str, data: bytes, final: bool = False) -> None: ...
    def close(self) -> None: ...


class ProcessObserver(Protocol):
    def output(self, stream: str, data: bytes, final: bool = False) -> None: ...
    def cancelled(self) -> bool: ...
    def heartbeat(self) -> None: ...


@dataclass(frozen=True)
class ProcessRequest:
    argv: Sequence[str]
    directory: Path
    environment: Mapping[str, str]
    timeout_seconds: float
    max_output_bytes: int
    run_id: str | None = None


class WorkflowProcess(Protocol):
    def execute(self, request: ProcessRequest, observer: ProcessObserver) -> int: ...
